### ISSUE TITLE
Global Styles on input fields are conflicting with the user's style

### ISSUE THREAD

**Issue by shivgarg5676** [upgrad/react-image-gallery#2]
There are few styles in styles.css which are conflicting with parent website's styles. please have them limited to its scope
```
input {
	border: 1px solid #e0e0e0;
	border-radius: 4px;
	padding: 0 10px;
	height: 40px;
	color: #4c4c56;
	resize: none;
	width: 100%;
	font-size: 14px;
	margin-bottom: 20px;
	transition: 200ms cubic-bezier(0.4, 0.14, 0.3, 1) all;
}
input:focus {
	border: 1px solid #298ee2;
	outline: none;
}
button {
		  border: none;
	    background: #2FCB53;
	    border-radius: 4px;
	    color: white;
	    cursor: pointer;
	    font-style: normal;
	    font-weight: bold;
	    font-size: 14px;
	    line-height: 19px;
	    text-align: center;
	    text-transform: uppercase;
}
button:focus {
	outline: transparent;
}
```

In apollo input:focus styles are conflicting with the material styles, more due to these sytes input components have a padding of 10px which is sometimes not desired. Since this file will be loaded on-demand at later stages it has higher precedence and css will override the already loaded styles

**Comment by kunalpanchal** [comment]
This is fixed on master branch. 

`button` is now `.galleryButton`
`input` is now `.galleryInput`
