### ISSUE TITLE
Image results disappear when tab is changed

### ISSUE THREAD

**Issue by mohitk05** [upgrad/react-image-gallery#3]
Search results on the `Search` tab disappear when tab is switched to `Upload new`. 

Steps to reproduce:
1. Search for something
2. Switch to upload new tab
3. Switch back to search

Images should have persisted, but actually do not.

**Comment by kunalpanchal** [comment]
Seems valid. Would you consider picking this up for next release?

**Comment by mohitk05** [comment]
Sure, picking it up!
